### ISSUE TITLE
Question about GPL license of xprintidle-plus

### ISSUE THREAD

**Issue by LocutusOfBorg** [pmaia/xprintidle-plus#1]
Hi pmaia, I open this issue, since your code is really useful for fixing a bug in linux/boinc program, but due of a license problem we cannot get it into, and it has been removed from the boinc mainline [1].

Is a problem asking you to bump the GPL version from v2 to v3?

That will be really nice for getting parts of your code inside boinc again!

Many thanks

Gianfranco

[1] http://boinc.berkeley.edu/gitweb/?p=boinc-v2.git;a=commitdiff;h=514484e0222834250b73fb8344a7a595778432f1

**Comment by pmaia** [comment]
Hey Gianfranco,

This code is not originally mine. I just made a small change to it in order to make it run in a infinite loop.
I'm not sure if I'm violating any license terms but I kept the original author information in the README file. Unfortunately it looks like the author's page is no longer available (http://www.dtek.chalmers.se/~henoch/text/xprintidle.html). Maybe you can have more luck with his email: Magnus Henoch henoch@dtek.chalmers.se

Patrick

**Comment by LocutusOfBorg** [comment]
Already tried to contact him. Didn't answer so far!
Thanks for your time
